// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package imagecontrol

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func InputFormImage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"p-6 mr-1 max-w-md w-full h-svh mx-auto bg-white shadow-sm shadow-gray-900 rounded-lg\"><form id=\"uploadImageForm\" class=\"space-y-4\" hx-post=\"/upload-image\" enctype=\"multipart/form-data\" hx-swap=\"innerHTML\" hx-target=\"#overview\"><div class=\"flex flex-col space-y-1\"><label for=\"inFile\" class=\"text-sm font-medium text-gray-700\">Input File</label> <input id=\"inFile\" type=\"file\" name=\"uploadedFile\" class=\"block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer focus:outline-none focus:ring-2 focus:ring-blue-500\"></div><div class=\"flex flex-col space-y-1\"><label class=\"text-sm font-medium text-gray-700\">Scale Algorithm</label> <select name=\"algorithm\" class=\"block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500\"><option value=\"nearest\">Nearest Neighbor Interpolation</option> <option value=\"bilinear\">Bilinear Interpolation</option> <option value=\"bicubic\">Bicubic Interpolation</option></select></div><button type=\"submit\" class=\"w-full rounded-md bg-blue-600 px-4 py-2 text-white font-medium hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500\">Submit</button></form><div id=\"overview\" class=\"mt-2\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
