// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: image.sql

package database

import (
	"context"
)

const addImageToTrack = `-- name: AddImageToTrack :one
INSERT INTO image_tracker (
  image_id,
  parent_version_id,
  filename,
  operation
) VALUES (?, ?, ?, ?) RETURNING id
`

type AddImageToTrackParams struct {
	ImageID         int64
	ParentVersionID int64
	Filename        string
	Operation       string
}

func (q *Queries) AddImageToTrack(ctx context.Context, arg AddImageToTrackParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addImageToTrack,
		arg.ImageID,
		arg.ParentVersionID,
		arg.Filename,
		arg.Operation,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const uploadImage = `-- name: UploadImage :one
INSERT INTO uploaded_image (
  filename,
  current_version_id
) VALUES ( ?, ?) RETURNING id
`

type UploadImageParams struct {
	Filename         string
	CurrentVersionID int64
}

func (q *Queries) UploadImage(ctx context.Context, arg UploadImageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, uploadImage, arg.Filename, arg.CurrentVersionID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
