// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type ImageTracker struct {
	ID              int64
	ImageID         int64
	ParentVersionID int64
	Filename        string
	Operation       string
	CreatedAt       sql.NullString
}

type UploadedImage struct {
	ID               int64
	Filename         string
	CurrentVersionID int64
	CreatedAt        sql.NullString
}
